cmake_minimum_required(VERSION 3.10)
project(hpc_opencl_opencv_demos LANGUAGES CXX)

find_package(OpenCV REQUIRED COMPONENTS core imgproc highgui calib3d)

add_executable(hpc_opencv_cl_camera camera.cc)
target_compile_features(hpc_opencv_cl_camera PRIVATE cxx_std_17)
target_link_libraries(hpc_opencv_cl_camera PRIVATE ${OpenCV_LIBS})
set_target_properties(hpc_opencv_cl_camera PROPERTIES OUTPUT_NAME opencv_cl_camera)

add_executable(hpc_opencv_cl_stereobm stereobm.cc)
target_compile_features(hpc_opencv_cl_stereobm PRIVATE cxx_std_17)
target_link_libraries(hpc_opencv_cl_stereobm PRIVATE ${OpenCV_LIBS})
set_target_properties(hpc_opencv_cl_stereobm PROPERTIES OUTPUT_NAME opencv_cl_stereobm)

add_executable(hpc_opencv_cl_test test_ocl.cpp)
target_compile_features(hpc_opencv_cl_test PRIVATE cxx_std_17)
target_link_libraries(hpc_opencv_cl_test PRIVATE ${OpenCV_LIBS})
set_target_properties(hpc_opencv_cl_test PROPERTIES OUTPUT_NAME opencv_cl_test)
