if(NOT CMAKE_CONFIGURATION_TYPES AND NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Build type" FORCE)
endif()

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC -Wall -O3")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -Wall -O3 -Wreorder")

# if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
# add_compile_options(-Wall -Wextra -Wpedantic)
# endif()

if(${CMAKE_CROSSCOMPILING})
  if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm|arm64|aarch64)")
    set(PLATFORM_ARCH aarch64)
    message(STATUS "\nCMAKE_CROSSCOMPILING for ARM \n")
  endif()
else()
  if(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(arm|arm64|aarch64)")
    set(PLATFORM_ARCH aarch64)
    message(STATUS "Building for ARM")
  elseif(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(x86_64)")
    set(PLATFORM_ARCH x86-64)
    message(STATUS "Building for x86-64")
  else()
    message(FATAL_ERROR "\n Unknown Architecture / CMAKE_SYSTEM_PROCESSOR !!! \n")
  endif()
endif()
